name: Create EC2 Instance

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  create-ec2:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ap-south-1

    - name: Create EC2 Instance
      run: |
        # Use AWS CLI commands to create an EC2 instance
        aws ec2 run-instances --image-id ami-0287a05f0ef0e9d9a --instance-type t2.micro --key-name windows-key --security-group-ids sg-00d739126791f1ed0 --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=GitHub_runner}]"
